### ISSUE TITLE
- [ ] Realizar cuadro de objetos aplicando metodología OOUX

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_ln_ppi2020#12]

**Comment by juanpablourrego14** [comment]
![Mapa OOUX](https://user-images.githubusercontent.com/68135148/89836721-f98c8000-db2c-11ea-82c3-ed061f83fbb9.png)

Buenas tardes profe este es mi trabajo de cuadro de objetos.  Feliz tarde
