### ISSUE TITLE
- [ ] Diseño del modelo entidad-relación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_ln_ppi2020#16]

**Comment by JohnFlorez25** [comment]
@juanpablourrego18 @juanpablourrego14 para dentro de 8 días deben tener la evidencia del Modelo entidad relación en la wiki, esta actividad la han venido desarrollando con la profesora Silvia y es ella quien les debe aprobar y validar dicho modelo. Adjunto imagen de ejemplo
![modelo-e-r](https://user-images.githubusercontent.com/22262727/93807644-86d4f100-fc10-11ea-8a9b-1c24f514edb2.png)

**Comment by juanpablourrego14** [comment]
![Untitled Diagram-Page-1](https://user-images.githubusercontent.com/68135148/97215179-1f234000-1792-11eb-8432-c620471b01bd.png)

**Comment by juanpablourrego14** [comment]
jhon faber aca le mando el modelo entidad relación
