### ISSUE TITLE
- [ ] Diseñar el diagrama de espina de pescado

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_ln_ppi2020#2]

**Comment by JohnFlorez25** [comment]
<img width="449" alt="2  Cuadrante_Uno_Aprobado" src="https://user-images.githubusercontent.com/22262727/88580768-bd77fc00-d011-11ea-8dd4-d89968d80463.png">

**Comment by JohnFlorez25** [comment]
<img width="449" alt="2  Cuadrante_Uno_Aprobado" src="https://user-images.githubusercontent.com/22262727/88580835-dbddf780-d011-11ea-9e53-6821c3456fd8.png">

**Comment by juanpablourrego14** [comment]
[CamScanner 07-22-2020 17.09.36.pdf](https://github.com/JohnFlorez25/equipo1_ln_ppi2020/files/5018199/CamScanner.07-22-2020.17.09.36.pdf)

**Comment by JohnFlorez25** [comment]
El diagrama cumple con el problema a abordar, se tienen en cuenta las distintas causas de acuerdo al problema identificado.
