### ISSUE TITLE
- [ ] Declarar la situación del problema

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_ln_ppi2020#3]

**Comment by juanpablourrego14** [comment]
[CamScanner 08-03-2020 15.40.13.pdf](https://github.com/JohnFlorez25/equipo1_ln_ppi2020/files/5018409/CamScanner.08-03-2020.15.40.13.pdf)

**Comment by juanpablourrego14** [comment]
Declaración de la situación
 Los vehículos de sao6 han reportado retrasos en sus rutas debido al mal estacionamiento en las vías de circulación la cual imposibilita la movilidad aumenta los índices de tráfico en las rutas establecidas
