### ISSUE TITLE
- [ ] Describir cada uno de los interesados

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_ln_ppi2020#4]

**Comment by juanpablourrego14** [comment]
[CamScanner 07-31-2020 17.27.23.pdf](https://github.com/JohnFlorez25/equipo1_ln_ppi2020/files/5018223/CamScanner.07-31-2020.17.27.23.pdf)

**Comment by JohnFlorez25** [comment]
Los interesados están correctamente identificados de acuerdo al problema
