### ISSUE TITLE
- [ ] Construir Tablero de Visión del Producto

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_ln_ppi2020#5]

**Comment by juanpablourrego14** [comment]
[CamScanner 08-03-2020 15.20.16.pdf](https://github.com/JohnFlorez25/equipo1_ln_ppi2020/files/5018286/CamScanner.08-03-2020.15.20.16.pdf)

**Comment by JohnFlorez25** [comment]
@juanpablourrego14 @juanpablourrego18 Cumple con el tablero de visión del producto
