### ISSUE TITLE
- [ ] Validar con 5 usuarios la viabilidad del proyecto

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_ln_ppi2020#6]

**Comment by juanpablourrego14** [comment]
[CamScanner 07-31-2020 17.27.23.pdf](https://github.com/JohnFlorez25/equipo1_ln_ppi2020/files/5018216/CamScanner.07-31-2020.17.27.23.pdf)

**Comment by juanpablourrego14** [comment]
[CamScanner 07-31-2020 17.27.23.pdf](https://github.com/JohnFlorez25/equipo1_ln_ppi2020/files/5018229/CamScanner.07-31-2020.17.27.23.pdf)

**Comment by JohnFlorez25** [comment]
Se evidencia la validación con los 5 usuarios para garantizar la viabilidad del proyecto
