### ISSUE TITLE
- [ ] Hacer mapa de Historia de Usuarios

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_ln_ppi2020#9]

**Comment by juanpablourrego14** [comment]
![Mapa de historia de usuario](https://user-images.githubusercontent.com/68135148/89839066-7110de00-db32-11ea-88c2-89fda0c3cea2.png)

Buenas tardes profe aquí le mando la tarea de Mapa de historia de usuario.  Feliz tarde profe

**Comment by JohnFlorez25** [comment]
@juanpablourrego14 @juanpablourrego18 buen trabajo
